name: repo_mirroring

on:
  push:
    branches: master

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-BDX-2-1-bschocolatine-florian.garde.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}

  to_codecommit:
   runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-BDX-2-1-bschocolatine-florian.garde.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
          ssh_username:                                 # <-- (for codecommit) you need to specify ssh-key-id as ssh username.
            florian.garde@epitech.eu                    #${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}



